# Artificial Neuronal Network

## Importing the libraries


In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.12.0'

# Part 1 - Data Preprocessing

## Importing the dataset (choose only one option)

### Option 1: from Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')
dataset = pd.read_csv('/content/drive/MyDrive/Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)

Mounted at /content/drive
[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


### Option 2: from Local Computer 

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)

## Encoding Categorical Data

## Label Encoding the "Gender" column


In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


## One hot encoding the "Geography" column


In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Splitting the dataset into the Training set and Test set


In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

## Feature Scaling


In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Part 2 - Building the ANN

## Initializing the ANN


In [7]:
ann = tf.keras.models.Sequential()

## Adding the input layer and the first hidden layer


In [8]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding the second hidden layer


In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding the output layer


In [10]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Part 3 - Training the ANN

## Compiling the ANN


In [11]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


## Training the ANN on the Training set


In [12]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5291 - accuracy: 0.7728
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4593 - accuracy: 0.7961
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4369 - accuracy: 0.8008
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4255 - accuracy: 0.8129
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4182 - accuracy: 0.8201
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4130 - accuracy: 0.8221
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4080 - accuracy: 0.8236
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4025 - accuracy: 0.8264
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3944 - accuracy: 0.8335
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3813 - accura

# Part 4 - Making the predictions and evaluating the model


## Predicting the result of a single observation


In [13]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)


1/1 [==============================] - 0s 74ms/step
[[False]]


## Predicting the Test set results


In [14]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),
                      y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 920us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix


In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1525   70]
 [ 201  204]]


0.8645